// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:5597331c-9edf-46ed-b246-220393c970b5",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_tkBARyCgn",
    "aws_user_pools_web_client_id": "39incmq82adglfgec56gs4g2lo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://aa57dyn2qndxdef3kp2v74bjka.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
